# FILE: EncarScraper/backend/config.py
import os

class Config:
    """Base configuration."""
    SECRET_KEY = os.getenv('SECRET_KEY', 'a_super_secret_key')
    
    # --- Database Configuration ---
    # This points to the SQLite database generated by your scraper
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATABASE_FILE = f"sqlite:///{os.path.join(PROJECT_DIR, 'data', 'encar_cars_output.db')}"
    SQLALCHEMY_DATABASE_URI = DATABASE_FILE
    SQLALCHEMY_TRACK_MODIFICATIONS = False# FILE: EncarScraper/backend/config.py
import os

class Config:
    """Base configuration."""
    SECRET_KEY = os.getenv('SECRET_KEY', 'a_super_secret_key')
    
    # --- Database Configuration ---
    # This points to the SQLite database generated by your scraper
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATABASE_FILE = f"sqlite:///{os.path.join(PROJECT_DIR, 'data', 'encar_cars_output.db')}"
    SQLALCHEMY_DATABASE_URI = DATABASE_FILE
    SQLALCHEMY_TRACK_MODIFICATIONS = False